### ISSUE TITLE
Could mockito provide an URL macro

### ISSUE THREAD

**Issue by bbigras** [lipanski/mockito#118]
something like:

```rust
let url = mockurl!("https://api.twitter.com");
```

instead of:

```rust
#[cfg(not(test))]
let url = "https://api.twitter.com";

#[cfg(test)]
let url = &mockito::server_url();
```

that would do the same thing.

**Comment by lipanski** [comment]
@bbigras thanks for raising the issue. mid/long-term I'm looking into getting rid of those compiler flags entirely in favour of using one or more server variables per test - see the discussion around https://github.com/lipanski/mockito/issues/92 which enables several other things (among which full parallel tests). for this reason I don't think it's worth adding such a macro right now.

**Comment by bbigras** [comment]
Perfect. Thanks!
