### ISSUE TITLE
Replace `difference` crate

### ISSUE THREAD

**Issue by GeorgeHahn** [lipanski/mockito#132]
The `difference` crate is listed in rustsec as unmaintained: https://rustsec.org/advisories/RUSTSEC-2020-0095.html. This isn't particularly critical, but it causes downstream users to get rustsec advisories for having a mockito dependency.

Upstream issue: https://github.com/johannhof/difference.rs/issues/45

**Comment by lipanski** [comment]
@GeorgeHahn are you experiencing any compatibility issues or is this more about the warning message? PRs for upgrading to a similar crate are more than welcome.

**Comment by GeorgeHahn** [comment]
@lipanski Yep, this is only about the warning message/rustsec github issues for downstream users. I'm not terribly concerned from a security perspective because this is usually a dev dependency. I added this work to my list, but I can't promise I'll get to it soon. I'll send a PR if I do!

Thank you for the awesome crate by the way :)
