### ISSUE TITLE
Non-Accessible Mocking Without Starting Forward Slash In Path?

### ISSUE THREAD

**Issue by criminosis** [lipanski/mockito#141]
I can see this being arguably written off just as a PEBKAC situation but wanted to share.

In short I neglected to have a starting forward slash in the path. The mock seemed okay with this but if the initial forward slash is required this seems to be creating a non-accessible mock? This consumed a lot of time until I narrowed it down to the mock path missing that forward slash.

```
fn main() {
    let path = "hello"; //No forward slash. Outputs: Response = (501, "")
    // let path = "/hello"; //works Outputs: Response = (201, "world")
    let _m = mock("GET", path)
        .with_status(201)
        .with_header("content-type", "text/plain")
        .with_header("x-api-key", "1234")
        .with_body("world")
        .create();

    let response = reqwest::blocking::get("http://localhost:1234/hello").unwrap();
    let message = (response.status(), response.text().unwrap());
    println!("Response = {:?}", message);
}
```

Off the cuff thinking some ways to help a future dev that hits this:
1. Instead of taking in a `&str` maybe it should take a struct that validates the provided input and returns an error if it was invalid?
2. Check for the forward slash and add it if missing (if no starting forward slash is otherwise meaningless)
3. Log a warning or error (though this is reliant on a logger running)
4. Panic if no forward slash (again only if no forward slash is meaningless, and you don't want to change the return type to a result)

**Comment by lipanski** [comment]
Thanks for reporting and for the suggestions. I don't think this requires any fix though, since it's the first time I hear of such an issue. I empathize with you about the time you've wasted, but my intention is to keep the library light at the moment.

**Comment by eeclfrei** [comment]
I also ran into this issue on a separate occasion, and agree it did seem a bit non-intuitive to get back a 501 here.  Thought that it would probably prepend initial `/` if not supplied.

**Comment by criminosis** [comment]
@lipanski that's one more instance that it impacted someone. Does that change your stance?
