### ISSUE TITLE
path matcher is sensitive to query param delimiter

### ISSUE THREAD

**Issue by imalsogreg** [lipanski/mockito#143]
`stripe-rs` rust http client appends `?` to all the paths it produces, even when it doesn't go on to specify any query parameters. The mock service we wrote for stripe failed to match because we didn't realize the client code was generating and extra '?' and that mockito would consider a path with an extra '?' to be a mismatch.

Would you be open to a PR that makes matching flexible over this case? If so, would you prefer that it simply treats `/foo` and `/foo?` identically? Or would it be better to generalize this, so that for example `/foo?a=1&b=2` would accept `/foo?b=2&a=1`?

```
#[tokio::main]
async fn main() {
    let mock = mockito::mock("GET", "/hello").with_body("good bye").create();

    let url = format!("{}/hello?", mockito::server_url());
    let response = reqwest::get(url.as_str()).await.unwrap();
    mock.assert();
    println!("{:?}", response);
}
```

```
> The last unmatched request was:

GET /hello?
accept: */*
host: 127.0.0.1:1234

> Difference:

GET /hello
GET /hello?
accept: */*
host: 127.0.0.1:1234
```

**Comment by lipanski** [comment]
@imalsogreg I think you have a few options as is:

(1) include the `?` in the mocked path:

```rust
#[test]
fn test_trailing_question_mark() {
    let _m1 = mock("GET", "/test?").with_body("matched").create();

    let (_, _, body) = request("GET /test?", "");
    assert_eq!(body, "matched");
}
```

(2) use the `match_query` function on your Mock with either `Matcher::Any` or one of the other [matchers](https://docs.rs/mockito/0.30.0/mockito/enum.Matcher.html), like `Matcher::AnyOf` or `Matcher::AllOf` combined with `Matcher::UrlEncoded` or even `Matcher::Regex` (check the docs/tests for some examples):

```rust
#[test]
fn test_trailing_question_mark() {
    let _m1 = mock("GET", "/test")
        .match_query(Matcher::Any)
        .with_body("matched")
        .create();

    let (_, _, body) = request("GET /test?", "");
    assert_eq!(body, "matched");
```

will do this the trick for you or is there an edge case I'm missing here?
