### ISSUE TITLE
Help: Cannot migrate to v1

### ISSUE THREAD

**Issue by ymwjbxxq** [lipanski/mockito#170]
Hello all,

currently, I am using version `mockito = "0.31"` and my unit tests are passing 

```
//CODE
...
        #[cfg(not(test))]
        let uri = format!(
            "{search_domain}/{search_index}/_search?size={page_size}&pretty=true",
            page_size = PAGE_SIZE,
            search_domain = &self.search_domain,
            search_index = &self.search_index
        );
        #[cfg(test)]
        let uri = format!("{}/endpoint", mockito::server_url());
...

//UNIT TEST
....
// ARRANGE
        let _m = mock("GET", "/endpoint")
            .with_header("content-type", "application/json")
            .with_body("{\"took\": 11,\"timed_out\": false,\"_shards\": {\"total\": 5,\"successful\": 5,\"skipped\": 0,\"failed\": 0},\"hits\": {\"total\": {\"value\": 1,\"relation\": \"eq\"},\"max_score\": 6.875992,\"hits\": [{\"_index\": \"shortener-stage\",\"_id\": \"07097514-4ec3-53e6-8d12-daa4f969bfcd\",\"_score\": 6.875992,\"_source\": {\"path\": \"/ciao\",\"target\": \"https://ciao.com\"}}]}}")
            .create();
```

If I convert to v1 in this way:
```
        #[cfg(test)]
        let uri = format!("{}/endpoint", mockito::Server::new().url());
 ```
 
 I get this error:
`reqwest sdk error reqwest::Error { kind: Decode, source: Error(\"EOF while parsing a value\"`

Could you please help me to understand what the problem is? Do you know if I miss a configuration? 

Thanks,
Dan

**Comment by lipanski** [comment]
You have to hold a reference to `mockito::Server` and use that to create your mocks and call `.url()`:

```rust
let mut server = mockito::Server::new();
server.mock("GET", "/endpoint").with_body("hello").create();

#[cfg(test)]
let uri = format!("{}/endpoint", server.url());
```

These days, every server can have its own URL and mocks.

See the [migration instructions](https://github.com/lipanski/mockito/releases/tag/1.0.0) or [the docs](https://docs.rs/mockito/latest/mockito/) for more details.

**Comment by evbo** [comment]
@lipanski is there anyway to keep the code as close as possible to pre-1.0? For instance, can we configure a static URL and port?

It's nice having `#cfg(test)` to override production but having to keep a mutable reference to the server makes that challenging.
