### ISSUE TITLE
expect 0 fails on assert

### ISSUE THREAD

**Issue by vasilakisfil** [lipanski/mockito#178]
If one sets `expect(0)` and then asserts the mock, an error will appear: `could not retrieve enough information about the remote mock`. The same goes for `matched`.

Apparently, the code inside `Mock` always checks for [get_mock_hits](https://github.com/lipanski/mockito/blob/master/src/server.rs#L85) (which is always `None` in the aforementioned case) and assumes that it will/should be `Some`.

Sounds like a bug to me, or at least, a limitation. One should be able to assert that _no_ requests were made to a 3rd part service.

**Comment by lipanski** [comment]
Expecting 0 definitely works:

```
#[test]
fn test_expect_zero() {
    let mut s = Server::new();
    let mock = s.mock("GET", "/hello").expect(0).create();

    mock.assert();
}

#[test]
#[should_panic(expected = "\n> Expected 0 request(s) to:\n\r\nGET /hello\r\n\n...but received 1\n")]
fn test_expect_zero_fail() {
    let mut s = Server::new();
    let host = s.host_with_port();
    let mock = s.mock("GET", "/hello").expect(0).create();

    request(&host, "GET /hello", "");

    mock.assert();
}
```

...so there's something else happening there. Are you sure you've called `.create()` or `.create_async()` correctly? Or are you mixing sync/async code by any chance? Could you share some code to reproduce this?

**Comment by vasilakisfil** [comment]
Indeed you are right, I wasn't calling the `create` method. Potentially a `#[must_use]` could be helpful here.

**Comment by lipanski** [comment]
There used to be a `#[must_use]` but now that we have a `create_async()` method on top it became obsolete :crying_cat_face: 

I'll see if I can tune the error messages.
