### ISSUE TITLE
Feature Request: Option to Start a Server on a different Socket Address

### ISSUE THREAD

**Issue by ajoklar** [lipanski/mockito#189]
I am currently using Mockito in tests which works great. 

I'd like to reuse my Mockito configurations for a binary application that runs a server with existing mock endpoints and exposes it to the local network. Therefore an option would be needed to bind the server to i.e. 0.0.0.0 instead of localhost.

The use case is that the mock backend can be called from Android emulators/devices and iOS devices.

**Comment by lipanski** [comment]
should be fairly easy to expose this, hope I'll have a look later in the week

**Comment by lipanski** [comment]
@ajoklar I implemented this in https://github.com/lipanski/mockito/pull/191 which landed in `master` - please give it a try:

```rust
let opts = mockito::ServerOpts { host: "0.0.0.0", ..Default::default() };
let mut server = mockito::Server::new_with_opts(opts); 
// let mut async_server = Server::new_with_opts_async(opts).await
```
