### ISSUE TITLE
Why are you constraining the maximum version of `colored`

### ISSUE THREAD

**Issue by Nemo157** [lipanski/mockito#195]
I just noticed in the last docs.rs `cargo update` there was a downgrade of `colored`: https://github.com/rust-lang/docs.rs/pull/2426

This is from https://github.com/lipanski/mockito/pull/191 restricting the version constraint to `colored = ">=2.0.0, <2.1.0"`, but there doesn't seem to be any mention of why the 2.1 versions can't be used. This isn't causing problems right now, but is likely to cause issues in the future if other crates depend on `>=2.1.0` at some point.

**Comment by lipanski** [comment]
They bumped their MSRV to 1.70 in 2.1.0 and I didn't want to change that yet (mockito supports 1.68 atm). Will probably follow soon or as soon as there's breakage. Is this an issue for you?

**Comment by Nemo157** [comment]
It's not an issue currently, I just wanted to make sure it didn't become an issue. The recommendation for supporting a more restrictive MSRV than your dependencies is to [not constrain verisons](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-requirements) but instead test with a set of [locked dependencies](https://rust-lang.github.io/rfcs/3537-msrv-resolver.html#status-quo) to show that it is _possible_ to compile with the MSRV while not stopping downstream users without such an MSRV requirement from using more recent versions.
