### ISSUE TITLE
HTTP reason phrase is omitted from responses

### ISSUE THREAD

**Issue by alyssais** [lipanski/mockito#20]
The [HTTP 1.1 RFC](https://www.w3.org/Protocols/rfc2616/rfc2616.txt) defines a response status line like this:

> `Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF`

However, since Mockito switched to constructing HTTP responses manually, instead of through Hyper, it has omitted the reason phrase (and indeed has no way of setting it without either modifying the API to require it being specified by the user, or maintaining an internal mapping of status codes to reason phrases like Hyper does). This means that correctly implemented HTTP clients may fail to parse responses generated by Mockito. Hyper itself is one of these clients that can't understand Mockito responses.

**Comment by lipanski** [comment]
the RFC does state:

> The Status-Code is intended for use by automata and the Reason-Phrase is intended for the human user. The client is not required to examine or display the Reason-Phrase.

...but I'll see what I can do to fix this. most probably I'll append the reason based on an internal mapping so I don't have to break the current interface.

**Comment by alyssais** [comment]
> the RFC does state:

> > The Status-Code is intended for use by automata and the Reason-Phrase is intended for the human user. The client is not required to examine or display the Reason-Phrase.

Sure, but it's still a mandatory part of the status line — even if a parser just skips over it, it can still expect it to be there.

Thanks in advance for looking into this. :) One thing you _could_ do would be to just return the same static string all the time, since a client is unlikely to depend on the value, but there does need to be _something_ there to be valid HTTP.

**Comment by lipanski** [comment]
I guess I misinterpreted that. in any case, [0.8.1](https://github.com/lipanski/mockito/releases) fixes it.
as always, thanks for reporting :1st_place_medal:
