### ISSUE TITLE
Feature Request: Option to remove a mock after expected criterion is fulfilled

### ISSUE THREAD

**Issue by Simon-Brummer** [lipanski/mockito#202]
Hi,

I am using Mockito to create mocks to testing a REST interface. The code I want to test implements a retrying behavior on failure.
To do this, I need two mocks matching the same request, the first Mock should accept three Request returning error response, the next Call on should return Status Code okay. The application is designed in a way that I can't reset the mock manually between REST API calls.

To do this properly it would be great to add an option that deletes the mock as soon as it was called the expected amount if times.

Or is there any other way to achive this? From the API I don't see one

**Comment by lipanski** [comment]
Hey @Simon-Brummer I think this should work for you:

```rust
let mut s = mockito::Server::new();
let first_three_calls = s.mock("GET", "/hello").expect(3).with_status(400).with_body("error").create();
let any_other_calls = s.mock("GET", "/hello").with_status(200).with_body("success").create();
```

When multiple mocks match a request, the request is served with the first one that matches (in order of their definitions). Mocks that fulfilled all the _expected_ calls are ignored (see [this](https://github.com/lipanski/mockito/blob/f1c3fe1b7ff1f0f2c1de07bf8251a39f5befa777/src/server.rs#L534)).

Note that my example is using the sync methods, prefer `Server::new_async` and `Mock::create_async` if you're writing async code.

**Comment by lipanski** [comment]
You can also check these [tests](https://github.com/lipanski/mockito/blob/f1c3fe1b7ff1f0f2c1de07bf8251a39f5befa777/tests/lib.rs#L1942-L1988) and note the usage of `expect_at_least` if you want your second mock to match not just the fourth call but any subsequent call.

**Comment by Simon-Brummer** [comment]
Hi @lipanski,

Thanks for your input as it solves my problem. Also I did some testing. In order to clear the mock you have to call expect. If you don't / relay on the default expectency of 1, then the mock is not cleared after reaching it. If this behavior is a bug or not is up to you to decide. At least I was confused that because I thought, not call expect has the same effect than calling expect(1).

Still thanks for helping me that quickly. You have a great library there.

**Comment by lipanski** [comment]
> At least I was confused that because I thought, not call expect has the same effect than calling expect(1).

That holds for `assert()` calls but, if I remember correctly, when we added the clearing behaviour on top the intention was to be explicit and keep things backwards compatible.

I guess you don't need `expect_at_least` on that second mock in that case - unless you intend to use `assert()`.

Will close this issue for now.
