### ISSUE TITLE
`with_header_from_request` for mock server

### ISSUE THREAD

**Issue by alex-kattathra-johnson** [lipanski/mockito#207]
The ability to respond with a specific header based on request.

**Comment by lipanski** [comment]
Not sure I understand what you mean - can you explain what you're missing? The library already provides a way to respond with a specific header (check the docs).

**Comment by alex-kattathra-johnson** [comment]
I want to respond with a `Sec-WebSocket-Accept` header based on the key that is sent in the request header.

**Comment by lipanski** [comment]
Got it, so you need to set the response header to a dynamic value, like in `Mock::with_body_from_request`. I think this library could acommodate something like `Mock::with_header_from_request` with a similar signature. PRs are welcome ;)

**Comment by alex-kattathra-johnson** [comment]
@lipanski: Got you a PR! :D

**Comment by lipanski** [comment]
@alex-kattathra-johnson Looks great, thanks.

Released as 1.6.1
