### ISSUE TITLE
Convert `From<&Path>` `Matcher` implementation to `TryFrom<&Path>`

### ISSUE THREAD

**Issue by szokeasaurusrex** [lipanski/mockito#209]
The [docs suggest](https://docs.rs/mockito/latest/mockito/enum.Matcher.html#impl-From%3C%26Path%3E-for-Matcher) that the current `From<&Path>` implementation is infallible, but, by inspecting the source code, we see that the implementation can panic:

https://github.com/lipanski/mockito/blob/649b97a2610c35ef552fbb0ffaf44c65abfa4601/src/matcher.rs#L58-L64

At a minimum, this behavior should be documented. But, it would likely be better to remove this `From<&Path>` implementation (likely a breaking change, so maybe we can deprecate it first), and instead replace it with a `TryFrom<&Path>` implementation, which allows users to decide how they wish to handle the case where we cannot read from the path.

**Comment by lipanski** [comment]
This is a testing library and the intention here is to warn the developer right away that their test is broken and to correct the path. I haven't seen the need to handle this as a `TryFrom` because I haven't seen a use case for it so far and handling a broken path in a test sounds quite defensive to me. How exactly does this affect your code base?

Also note that the library uses panics in several other places for the same practical reasons.

**Comment by szokeasaurusrex** [comment]
@lipanski it is more that the API should communicate the expected behavior. If something implements `From<T>`, I would expect the conversion to always succeed, since that is the idiomatic pattern in Rust. If the conversion could fail in some way, then the object should implement `TryFrom<T>` so that the developer of the application/test, can decide how I want to handle the failure. 

I did notice that the library is using panics in many other places as well; I am now considering switching to a different mocking library for this reason, since I would rather use a library which adheres to the more typical Rust error handling patterns. I think only the functions which are explicitly performing some sort of assertion should panic; otherwise, the test author should decide how to handle the case of a failure, not the mocking library. Having panics all over the place makes it, in my opinion, harder to understand where failures can arise from, and it makes `mockito` less flexible, since developers using the library cannot easily override the panicking behavior.

At a minimum, this `unwrap` should be replaced with an `expect` that has a helpful error message, something along the lines of "Error: Could not open /path/to/file." But really, using `TryFrom` would be a much clearer approach here imo.

**Comment by lipanski** [comment]
The idea of using unwraps in a testing library allows you to write more ergnomic, less defensive tests. It's probably one of the few places where you can get away with it and it makes for a nicer interface.

The other thing that the library does to make the most out of the unwraps is implementing [implicit caller location](https://rustc-dev-guide.rust-lang.org/backend/implicit-caller-location.html) to ensure (for most parts) accurate signaling of the error cause. This is unfortunately not possible in async code atm.

On the aspect of `expect` vs. `unwrap`, let's have a look at the current error. Given this code (note line 1037):

![screenshot-2024-11-19_21-36-17](https://github.com/user-attachments/assets/75a74016-f956-44c8-bef2-6516a05c0a82)

...this is how the panic would look like:

```
---- test_body_from_file stdout ----
thread 'test_body_from_file' panicked at tests/lib.rs:1037:10:
called `Result::unwrap()` on an `Err` value: Error { kind: FileNotFound, context: None }
```

I think that's quite revealing - you have both the error type `FileNotFound` and the line number in there. If you want something more explicit feel free to open a PR though.

So I'll ask again - how does this affect your tests? Are they easier to write and less verbose? I'd say so. Are they much harder to debug than if you wrote that `unwrap` yourself in the test? That's up to you to decide and you're obviously free to try different libraries and find the right balance.
