### ISSUE TITLE
Non-panicking `Mock::assert` alternative

### ISSUE THREAD

**Issue by szokeasaurusrex** [lipanski/mockito#210]
I have a use case where I have multiple mocks I would like to assert using [`Mock::assert`](https://docs.rs/mockito/latest/mockito/struct.Mock.html#method.assert), and I also am running other assertions to make sure my code worked as expected. I would like to see all of the failed assertions, both for the mocks and my other assertions, but I can only see at most one assertion from `Mock::assert`, because `Mock::assert` panics if the assertion fails.

It would be helpful to have another function (perhaps named `Mock::assert_result`) which returns a `Result`. Instead of panicking, if the assertion fails, and `Err` including the assertion message would be returned. Then, the calling code could gather all of the errors and display them.

Note that the [`Mock::matched`](https://docs.rs/mockito/latest/mockito/struct.Mock.html#method.matched) method is insufficient for my use case because it provides no way for me to obtain the message generated by `Mock::assert` in the failure case.

**Comment by lipanski** [comment]
If `Mock::matched` is not enough and as I don't intend to expose the internals for generating the `Mock::assert` messages any time soon, your best bet is probably [catch_unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html):

```rust
use std::panic::{catch_unwind, AssertUnwindSafe};

fn main() {
    let mut server = mockito::Server::new();
    let m = server.mock("GET", "/a").with_body("hello").create();

    // v1: Assumes the entire closure is unwind safe
    let _ = catch_unwind(AssertUnwindSafe(|| {
        m.assert();
    }));

    // v2: Assumes only the mock variable is unwind safe
    let unwind_safe_mock = AssertUnwindSafe(&m);

    let _ = catch_unwind(move || {
        (**unwind_safe_mock).assert();
    });
}
```
