### ISSUE TITLE
Diff between executed and expected requests

### ISSUE THREAD

**Issue by andir** [lipanski/mockito#23]
When looking at the output of (failed) tests it isn't immediately visible what might be different.
For example larger JSON blobs or subtle changes in headers can take quite some time to spot.

**Comment by lipanski** [comment]
are you talking about the `Mock#assert` error message? [this one](http://lipanski.github.io/mockito/generated/mockito/index.html#example-4)? if so, I might be able to add some colouring of what's different, though there are actually two situations to consider here:

- the last unmatched request is mocked wrongly (there is a mock but its too strict for the request)
- the last unmatched request is not mocked at all (in which case the diff is basically the entire unmatched request)

**Comment by andir** [comment]
Yes, that is what I mean. Basically telling the user what part of the request and maybe even the values/body is wrong.

**Comment by otavio** [comment]
I believe https://crates.io/crates/difference might help to add this feature.

**Comment by lipanski** [comment]
Relased with https://github.com/lipanski/mockito/releases/tag/0.12.0
