### ISSUE TITLE
Underscore variables

### ISSUE THREAD

**Issue by filib** [lipanski/mockito#27]
When I set up my mock but I only use an underscore as the variable (see example below), the mock doesn't get created. Why does this happen when I use `let _` but not `let _m`? Is the call being optimised away by the compiler? Is it worth adding a note in the documentation?

``` rust
  let _ = mock("GET", "/recordings?device_id=0000")
    .with_status(201)
    .with_header("content-type", "text/plain")
    .with_body(json_body) // some json string
    .create();
```

## Versions

```
rustc 1.22.0-nightly (d7e73e4b1 2017-10-04)
mockito-0.9.0
```

**Comment by lipanski** [comment]
good point. I've clarified this in https://github.com/lipanski/mockito/commit/1205b591e4d618b5c4985d76ee38e0dcbd40ce52

I'm actually not sure why Rust treats the `_` this way, but it's definitly a consistent behaviour. I've found [this RFC](https://github.com/rust-lang/rfcs/pull/1177) but I'm still not exactly sure what the story behind this is.

**Comment by ozkriff** [comment]
> I'm actually not sure why Rust treats the _ this way

`_` isn't even a variable (binding), it's just a part of a pattern matching syntax, like `mut`, `ref`, `|` etc.

**Comment by lipanski** [comment]
@ozkriff good point. I tried to be more correct in https://github.com/lipanski/mockito/commit/55d36f3fc1eeb8e08a690d3feea275fdc5f52163
