### ISSUE TITLE
Mediate access to mock server with a mutex

### ISSUE THREAD

**Issue by Diggsey** [lipanski/mockito#29]
The docs currently recommend running tests with `--test-threads=1`, but this means that none of the tests can be run in parallel.

A simple solution without changing the design would be to take a global mutex whenever the first mock end-point is created on a thread, and release that mutex whenever the last mock end-point is dropped.

**Comment by lipanski** [comment]
it's not solving the core problem but it could allow tests not using mocks to perform in parallel, which is neat. would you be interested in making a PR?

**Comment by lipanski** [comment]
Closed by https://github.com/lipanski/mockito/pull/35
@Diggsey please let me know if this works for you. Also, if it happens that you're using mocks inside doctests, please check https://github.com/lipanski/mockito/issues/36
