### ISSUE TITLE
is it possible to add latency mocking?

### ISSUE THREAD

**Issue by spamwax** [lipanski/mockito#31]
Thanks for the very useful crate.

For testing purposes, I need to mock a server that will return a 200 response after, say, 400ms!
Is it currently possible to do it?

**Comment by lipanski** [comment]
this is not a feature of mockito per se, but you can do something like:

```rust
    std::thread::spawn(|| {
        std::thread::sleep(std::time::Duration::from_millis(400));
        let mock = mockito::mock("GET", "/hello").create();
        loop {};
    });
    
    // Run your code here
    // The "GET /hello" mock will only be available after 400ms
```

the `loop {}` at the end ensures that the mock doesn't get removed when the variable `mock` gets out of scope. you can replace it with some more clever mutex checks if you want, but this should work as well.
