### ISSUE TITLE
Test suite fails randomly (due to a possible race condition?)

### ISSUE THREAD

**Issue by kyrylo** [lipanski/mockito#38]
Hi, thanks for the library, it's fun and easy to use! 

I suspect I hit a bug with mockito 0.11.0. I have a small test suite of 3 tests and 50% of the time it fails. It may be a race condition, however it's just a wild guess since I'm very new to mockito and I don't know how exactly it works.

I am using the following code: https://github.com/kyrylo/airbrake-rust/tree/reboot
You can clone the repo (make sure to checkout the `reboot` branch, commit sha is `a6514530305c537a029af838a86cdef72fbeb948`) and run tests yourself. Here's a sample output:

<details>
  <summary>% cargo test -- --nocapture</summary>
 
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/airbrake-9afc2687bc83f1a7

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/airbrake-ac572b687ba1c60e

running 3 tests
thread 'it_notifies_airbrake' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`:
Expected 1 request(s) to:

POST /api/v3/projects/113743/notices
content-type: application/json

...but received 2

', /Users/kyrylo/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.11.0/src/lib.rs:677:44
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'it_attaches_a_backtrace' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`:
Expected 1 request(s) to:

POST /api/v3/projects/113743/notices
"backtrace":\[\{"line":\d+,"file":".+","function":".+".*\}\]

...but received 0

', /Users/kyrylo/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.11.0/src/lib.rs:677:44
test it_notifies_airbrake ... FAILED
test it_attaches_a_backtrace ... FAILED
thread 'it_attaches_params' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`:
Expected 1 request(s) to:

POST /api/v3/projects/113743/notices
"params":\{"banana":\{"String":"tasty"\},"mango":\{"Int32":42\}\}

...but received 0

', /Users/kyrylo/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.11.0/src/lib.rs:677:44
test it_attaches_params ... FAILED

failures:

failures:
    it_attaches_a_backtrace
    it_attaches_params
    it_notifies_airbrake

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test airbrake'
```
</details>

---

As you can see one of the tests outputs `...but received 2`, however I make only one HTTP request there. The call is in the same thread and it's synchronous (at least I can state that my library's code doesn't do anything clever in this department).

It's worth mentioning that if I comment [the last test](https://github.com/kyrylo/airbrake-rust/blob/a6514530305c537a029af838a86cdef72fbeb948/tests/airbrake.rs#L49-L75), then the other 2 tests pass consistently. Perhaps, the test is flawed? I can't see how it could be the case, but if it is, my apologies for the false report.

I would appreciate some assistance here. Thanks!

**Comment by lipanski** [comment]
@kyrylo thanks for reporting, I'll have a look

**Comment by otavio** [comment]
@kyrylo try using one thread to run the tests and see if it continue to happen? In my case, it gives different output if run in parallel or serial.

**Comment by kyrylo** [comment]
@otavio are you referring to the `--test-threads=1` option? It seems like it was removed in (or at least the need for it):
https://github.com/lipanski/mockito/commit/509a06f42889d3adbe8dbb8250c183edb9f68aeb

That said, I tried it and it still fails randomly, although with a slightly different error.

<details>
  <summary>% cargo test -- --nocapture --test-threads=1</summary>

```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/airbrake-ac572b687ba1c60e

running 3 tests
test it_attaches_a_backtrace ... ok
test it_attaches_params ... thread 'it_attaches_params' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`:
Expected 1 request(s) to:

POST /api/v3/projects/113743/notices
"params":\{"banana":\{"String":"tasty"\},"mango":\{"Int32":42\}\}

...but received 0

The last unmatched request was:

POST /api/v3/projects/113743/notices
host: 127.0.0.1:1234
user-agent: reqwest/0.8.5
accept: */*
content-type: application/json
authorization: Bearer 81bbff95d52f8856c770bb39e827f3f6
content-length: 156
accept-encoding: gzip
{"errors":[{"type":"ParseIntError","message":"invalid digit found in string","backtrace":null}],"params":{"mango":{"Int32":42},"banana":{"String":"tasty"}}}

', /Users/kyrylo/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.11.0/src/lib.rs:677:44
note: Run with `RUST_BACKTRACE=1` for a backtrace.
FAILED
test it_notifies_airbrake ... ok

failures:

failures:
    it_attaches_params

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test airbrake'
```
</details>

**Comment by otavio** [comment]
Yes. In my case using single thread makes it stable.

@lipanski seems to be the best to look why...

**Comment by lipanski** [comment]
@kyrylo I couldn't figure it out yet. the changes in `0.11.0` seem unrelated because I tried your branch with `0.10.0` and got similar flickering results. `--test-threads=1` doesn't solve it either (as you mentioned above). will try to debug further during the next week.

**Comment by lipanski** [comment]
ok, so I think I've solved it. there are two parts to this story:

(1) JSON responses coming from your code will randomly change the key order:

```
# Response with different key order
..."params":{"mango":{"Int32":42},"banana":{"String":"tasty"}}...

# Your mock
"params":{"banana":{"String":"tasty"},"mango":{"Int32":42}}
```

so the Regex matcher that you use in your tests won't work *all the time*. I suggest either figuring out a regular expression that can work around this key order problem or switching to `Matcher::JsonString` introduced with https://github.com/lipanski/mockito/releases/tag/0.11.1 - in which case you'll have to provide the entire JSON response String (but the order of keys shouldn't matter).

another option would be to enable [the preserve_order feature of serde](https://docs.serde.rs/serde_json/enum.Value.html#variant.Object), though I'm not sure you have this exposed in your code and I've never tried this out myself.

(2) when I tried to remove the need for `--test-threads=1` in https://github.com/lipanski/mockito/releases/tag/0.11.0 I had to use a little workaround - https://github.com/lipanski/mockito/blob/master/src/lib.rs#L729 - your test method names should start with `test_`. this is a Rust convention but I guess nothing is stopping you from chosing your own names. the reason for that piece of code is to block execution only of the parent test threads, not of any sub-threads. without this condition, Mockito wouldn't be able to support sub-threads or I'd have to go back to `--test-threads=1`.

I'm not particulary happy about it and I might figure out something better in the future, but in any case the current solution is to simply rename your test methods - turn them into something that starts with `test_`.

---

with 0.11.1 I also introduced a debug mode to Mockito, which you can enable by setting the `MOCKITO_DEBUG` environment variable. this should help debugging in the future.

**Comment by lipanski** [comment]
@kyrylo let me know if my previous comment solves your issues.

**Comment by otavio** [comment]
But the tests are already marked as `#[test]` so why putting `test_` prefix as a requirement?

**Comment by lipanski** [comment]
@otavio a PR is worth 1000 words - https://github.com/lipanski/mockito/pull/39

you can expand the ignored test to see what I mean. the test thread name was the only way (that I could figure out) to differentiate the main test threads from any of their sub-threads.

the PR removes the naming condition but you won't be able to create mocks from threads any more. not sure if that's such an important feature though.

thoughts?

**Comment by otavio** [comment]
What use case you can think about creating mocks from threads?

**Comment by lipanski** [comment]
@otavio things like https://github.com/lipanski/mockito/issues/26 (but I don't think it's very common so I'm not so into supporting it, unless proven otherwise). having different test function names sounds like more common and the outcome without https://github.com/lipanski/mockito/pull/39 can be more confusing to the user.

**Comment by lipanski** [comment]
I ended up merging #39 - simplifying things a bit but rendering it impossible to create mocks from within threads, which was a bit brittle anyway.

@kyrylo I recommend using [0.12.0](https://github.com/lipanski/mockito/releases/tag/0.12.0) and you'll only need to update your matcher (see my point (1) from my comment above). point (2) doesn't apply any more with the latest release.

**Comment by otavio** [comment]
Just to let you know that I upgraded to 0.12.0 and it works like a charm ;-)

**Comment by kyrylo** [comment]
Sorry for the late reply!

It looks like I was just misusing the library (the order issue). Thanks for digging into that, it didn't occur to me that the order could be different.

I was not aware of the `test_` convention. From now on I'm going to stick with it.

I had no luck with `preserve_order` (would be my most favourite solution), it doesn't seem to work for me (or I don't know how to enable it).

Matching the whole JSON body is a bad option because it makes tests brittle. I would need to update every single test when I change the JSON body and this sounds like a lot of tedious work.

I hoped that multiple `match_body` calls would work but that's not the case - only the last call gets registered.

Not sure what the best option is so far. Perhaps I need to dig into `preserve_order` more thoroughly.
