### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by kyrylo** [lipanski/mockito#40]
I use [reqwest](https://github.com/seanmonstar/reqwest) to make HTTP requests. Using that library...

...I specify a proxy server like this:

```rust
let mut client_builder = reqwest::Client::builder();
client_builder.proxy(reqwest::Proxy::all("http://127.0.0.1:8080")?);
```

...I write a mock like this:

```
let mock = mock("POST", "/api/v3/projects/113743/notices").create();
```

When I run my test, I get the following error:

```rust
Error {
    kind: Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }),
    url: Some("http://127.0.0.1:1234/api/v3/projects/113743/notices") 
}', libcore/result.rs:945:5
```

As you can see, the request goes to `http://127.0.0.1:1234`, which is `mockito::SERVER_URL`.

I have tried:

* **using multiple `mock` calls**
    I wanted to mock both the proxy URL and the mockito server. This doesn't work because apparently Mockito allows only 1 `mock` call per test. Compilation fails with:

    ```
    error[E0618]: expected function, found `mockito::Mock`
    ```

* **running my code without mockito**
    I setup a local proxy server (SquidMan for OSX). I can confirm if I run real requests routed to my proxy, it works as expected, so the problem doesn't seem to be related to my implementation

* **mocking only the proxy OR mocking only the mockito server**

    ```
    // Proxy
    let mock = mock("POST", "http://127.0.0.1:8080/api/v3/projects/113743/notices").create();

    // Mockito
    let mock = mock("POST", "http://127.0.0.1:1234/api/v3/projects/113743/notices").create();
    ```

    No luck either.

I have my real test [here](https://github.com/kyrylo/airbrake-rust/blob/76879a5e926240df5b4d95ed4d098c56ff7b4363/tests/airbrake.rs#L73-L88). Make sure to unignore it if you plan to run (checkout the `reboot` branch).

**Comment by lipanski** [comment]
@kyrylo 

> using multiple mock calls
> This doesn't work because apparently Mockito allows only 1 mock call per test.

the error `error[E0618]: expected function, found mockito::Mock` is produced because you called your variable `mock` which collides with the `mock` method.

```rust
# wrong
let mock = mock("GET", "/1").create();
let mock2 = mock("GET", "/2").create(); # mock refers to the mock variable here

# good
let m1 = mock(...).create();
let m2 = mock(...).create();

# also good (but more verbose)
let mock = mockito::mock(...).create();
let mock2 = mockito::mock(...).create();
```

---

I'd recommend - if possbile - testing the two parts of your app (the proxy and the proxied backend) in different tests or just mocking the proxy with the proxied backend response. this should be fairly easy:

```rust
let m1 = mock("POST", "http://whatever/api/v3/projects/113743/notices")
    .with_body("the backend response (the one that sits behind the proxy)")
    .create();
let notifier = airbrake::Notifier::new(airbrake::Config {
    project_id: 113743,
    project_key: "81bbff95d52f8856c770bb39e827f3f6",
    proxy_url: mockito::SERVER_URL, # we're mocking the proxy server here
    host: "http://whatever",
    ..Default::default()
});
m1.assert();
```

hope this helps.

**Comment by kyrylo** [comment]
That's awesome, thanks a lot! (and sorry for spamming your bug tracker with irrelevant issues).

**Comment by lipanski** [comment]
@kyrylo no problem :)
