### ISSUE TITLE
Verb <unknown> bug only occurs on 64-bit windows

### ISSUE THREAD

**Issue by lilith** [lipanski/mockito#41]
I'm encountering a bug that only occurs on 64-bit windows - it works fine on OS X, 32-bit windows, and 3 versions of ubuntu. Using rust beta-2018-06-30

```
GET /v1/licenses/latest/test8b47045eb7b8ca42aa967f33ee1d014ba89f8d1ac207426b482d34b5c0d90935.txt
...but received 0
The last unmatched request was:
<unknown> /v1/licenses/latest/test8b47045eb7b8ca42aa967f33ee1d014ba89f8d1ac207426b482d34b5c0d90935.txt
host: 127.0.0.1:1234
user-agent: reqwest/0.6.2
accept: */*
accept-encoding: gzip
```

https://ci.appveyor.com/project/imazen/imageflow/build/1067/job/ovesuwbxnqahed92#L617

code: 
https://github.com/imazen/imageflow/blob/6d00cf44fe90b29dbac0bfe0a1aca495b7c72535/imageflow_helpers/src/licensing/test/mod.rs#L122

Have you seen this?

**Comment by lipanski** [comment]
the appveyor 64-bit Windows tests for mockito seem fine. if you could update to 0.12 it would be interesting to run the tests with `MOCKITO_DEBUG=1 cargo test` (or just set the `MOCKITO_DEBUG` environment variable before running `cargo test`). this might help isolate the problem and see if it's some untested/buggy part of mockito or something else.

**Comment by lilith** [comment]
Thanks. I was using 0.12, I believe.
