### ISSUE TITLE
custom "Content-Length"

### ISSUE THREAD

**Issue by dherman** [lipanski/mockito#52]
For HTTP HEAD requests, the response can include a Content-Length indicating the size of the resource without actually returning the resource in the body. When I try setting `"Content-Length"` headers with `with_header()` and no body, mockito seems to append `", 0"` to the header.

I can try to do a PR to address this but it'd be good to know what the best solution would be. One possibility that I can think of is that the default behavior of computing the Content-Length from the body should be suppressed if the header is supplied explicitly via `with_header`.

**Comment by lipanski** [comment]
I'll have a look. thanks for reporting.

**Comment by lipanski** [comment]
@dherman took a while, but https://github.com/lipanski/mockito/pull/63 should do the job.

if you set `content-length` via `#with_header`, it will not be overriden any more. also, in the case of `HEAD` requests no body will be sent (previously the crate would either set an empty, 0 length body, or it would allow the developer to set a body, which I guess was wrong).

let me know if it works.
