### ISSUE TITLE
How to mock http download file?

### ISSUE THREAD

**Issue by xiaohulu** [lipanski/mockito#54]
```rust
let _m = mock("GET", "/").with_body_from_file("tests/files/simple.http");
```
use this method?

Thanks!

**Comment by lipanski** [comment]
@xiaohulu that should work. it sets `Content-Length` for you.

on the other hand, if you want to download via `transfer-encoding: chunked`, that might not work - or at least I've never tested it.

**Comment by xiaohulu** [comment]
Thanks!
