### ISSUE TITLE
Mock with latency?

### ISSUE THREAD

**Issue by nbigaouette-eai** [lipanski/mockito#64]
I'm mocking an API that returns a json with content saying if a previous query is running or completed. So I have to poll that API until the initial query is complete. For example:
* From 0 to X ms, `GET` on `/status` should return `{"status": "starting"}`
* From X to Y ms, `GET` on `/status` should return `{"status": "running"}`
* From Y ms and updward, `GET` on `/status` should return `{"status": "complete"}`

I want to test my exponential backoff until completion.

I'm not sure how to do this with mockito right now. Since all requests will be on the same route with the same information (only the return data will be different) I cannot create them all beforehand; how would mockito known which mock to use if they are all identical?

Issue #31 asked for something similar and a suggestion was to use threads to create the mocks. An `Arc<Barrier>>` can easily be used to synchronize threads (instead of a loop as suggested in #31).

I tried spawning a thread to create and destroy the mocks with the different behavior at the proper timing but got a deadlock. The lock happens at https://github.com/lipanski/mockito/blob/459049a780c49e8837c77cba047b76d5606b322e/src/lib.rs#L774

I also tried to put my client performing the `GET` in its thread instead and creating the mocks in the "main" test thread but this does not work since reqwest/tokio is not `Send`.

For now I'm kind of stucked... Any suggestion? Thanks!

**Comment by lipanski** [comment]
yup, the deadlock is a known issue, see https://docs.rs/mockito/0.15.1/mockito/#limitations and https://docs.rs/mockito/0.15.1/mockito/#threads (but there are reasons to keep it for now, especially the ability to run non-mockito tests in parallel).

(I'll have to think a bit more about a solution to your problem though)

**Comment by nbigaouette-eai** [comment]
I've hacked something to bypass this issue.

In the "main" test thread, I create all the mocks for the identical queries, with the different return values. I place those mocks in a vector in reverse order so that the last in the vector is the first one I want mockito to pick up and use.

This way, mockito will pick up the last mock of the vector to serve the reply. I then move the vector of mocks to a thread where I pop them from the vector and explicitly drop them one after the other and after waiting some time to mimick the latency. Once a mock is dropped, mockito will use the new last mock in the vec to answer a query.

In "main" test thread I then call my retry-backoff function. If everything is well aligned, it works. I've used an `Arc<Barrier>` to sync the two threads as to minimize issue with timing.

Happily enough I've found a small bug in the backoff that way (yay!) but this is a terrible hack. I'll leave the test in my code but I expect it to break at some point. I also wanted to reuse this testing in another test by refactoring to function some common functionality but the tests were failing so I've reverted back to a single test. A better, less hacky solution would surely be preferable!

I though that maybe the methods of the builder to define return values could take a function/closure to generate the values? For example instead of `mock(...).with_body("string body")` a new method could be `with_body_fn(|| { if ... { "begin" } else { "end" } })`?

Thanks for looking into this!

**Comment by kornelski** [comment]
I'd love something like `with_body_fn`, too.

I want to test how my code behaves while a request is in progress to ensure I don't have any race conditions, but to test that reliably in CI I need an artificially slow mock response.

If I could do `.with_body_fn(|| {thread::sleep(5sec); "boom"}` that would be great.

**Comment by liamdawson** [comment]
I want to test the parallelism of a function, to ensure my `rayon` iterator still returns the results in the order they appeared in the original iterator. I can't really test this without a delay.

**Comment by kornelski** [comment]
I've made a PR for this.

**Comment by lipanski** [comment]
Released with [0.19.0](https://github.com/lipanski/mockito/releases).
