### ISSUE TITLE
Are users supposed to run mockito-server?

### ISSUE THREAD

**Issue by ignatenkobrain** [lipanski/mockito#68]
I was looking at packaging of mockito for Fedora , but I am not sure if we need to package this binary or not.

**Comment by lipanski** [comment]
no, mockito is mainly user as a library (included inside other applications). running it as a binary was only meant for experimenting. not sure this answers your question.

**Comment by ignatenkobrain** [comment]
Yes it does... probably it can be moved to "examples" instead of `main.rs`?

**Comment by lipanski** [comment]
@ignatenkobrain that makes sense :+1:
