### ISSUE TITLE
Tests hang on window

### ISSUE THREAD

**Issue by afonso360** [lipanski/mockito#7]
Hi,

When I tried to test this library on windows it seems to hang and use 100% cpu time.
The hang can be reproduced on Appveyor

https://ci.appveyor.com/project/afonso360/mockito

I tracked the issue down to server.rs:143, when executing `server.handle()` it seems to hang.

The newer versions of hyper (git) don't hang on windows, would it be possible to upgrade?
The hyper api has changed slightly so it wouldn't be a matter of just changing Cargo.toml

I can probably try to submit a pull request if you want me to

**Comment by lipanski** [comment]
https://github.com/lipanski/mockito/pull/2 did upgrade the hyper version and appveyor was using the latest stable version of hyper - `0.10.4` - in your test run.

could it be that port `1234` is blocked/reserved/firewalled on Windows?

**Comment by afonso360** [comment]
I meant changing it to track git, which I believe has quite a few changes from the latest stable release because they changed to async i/o, ill try and get it working with the async version tonight.

I tried on my windows machine and even after enabling the port on the firewall the result was the same.
Also tried to change from 1234 to 8088 on appveyor and the result was the same.

**Comment by afonso360** [comment]
Changing to Async io is going to require a lot more changes than I thought, and I don't think i can do it now? do you have ideas on how to solve this?

**Comment by lipanski** [comment]
I'll have a look over the weekend but no promises. using unstable hyper is not an option I'd like to consider but maybe there are other ways to get this working on Windows.

**Comment by afonso360** [comment]
I agree, we shouldn't use unstable hyper, but if we don't find another option what we could do is, start a new branch tracking the Async I/O version of hyper and keep that as a separate branch until 1.0.0 is released.  We would then be ready with a working version for the next hyper release.

**Comment by lipanski** [comment]
hey @afonso360 

I've just released a major change to mockito, replacing hyper entirely with curl + http-muncher, which means it supports Windows builds from now on :)

appveyor is [nice and green](https://ci.appveyor.com/project/lipanski/mockito/history).

the new version is [0.5.0](https://github.com/lipanski/mockito/releases/tag/0.5.0) - please give it a try if you're still interested.

**Comment by lipanski** [comment]
Closed by https://github.com/lipanski/mockito/pull/16
