### ISSUE TITLE
Naming conflict with Mockito (Java)

### ISSUE THREAD

**Issue by Thoma5** [lipanski/mockito#70]
I found this lib coincidentally while taking my first steps in rust and wanted to make you aware of a possible naming conflict:
[Mockito](https://github.com/mockito) is a well known and widely used java mocking framework.

**Comment by lipanski** [comment]
I've also realised this at some point but the renaming ship had sailed the moment I got that awesome logo :)

I expect most searches to come via crates.io so it's not that bad.
