### ISSUE TITLE
rand 0.6

### ISSUE THREAD

**Issue by ignatenkobrain** [lipanski/mockito#73]
Hello,

Maintainer of mockito in Fedora here. I would appreciate if you would update rand dependency to latest 0.6 so that we don't have to keep 0.5.x around anymore.

Thanks!

**Comment by JeanMertz** [comment]
I would like to see this happen as well. Rand 0.6 [adds support](https://github.com/rust-random/rand/pull/541) for the `wasm32` target with `wasm-bindgen`, which would allow me to use Mockito as a mocking library for [wasm-bindgen-based tests](https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/index.html).
