### ISSUE TITLE
Assert at least N requests

### ISSUE THREAD

**Issue by gakonst** [lipanski/mockito#79]
Currently `.expect(NUMBER)` & `.assert()` allow checking that an exact number of queries were made to a mock. It'd be nice if we could do `.check(CONDITION)` to check if there were at least N or no more than N requests, instead of an exact number

**Comment by lipanski** [comment]
you mean something like `fn expect_at_least(count: usize)` and `fn expect_at_most(count: usize)`? otherwise I don't really understand the point of a condition - please provide some more concrete examples.

**Comment by gakonst** [comment]
Yes, exactly. (pardon the bad phrasing, was late when I was writing up the issue)

**Comment by lipanski** [comment]
:+1: that shouldn't be hard to implement. PRs are welcome though :)

**Comment by frondeus** [comment]
I think this is ready to be closed

**Comment by lipanski** [comment]
@frondeus indeed.

Released in https://github.com/lipanski/mockito/releases/tag/0.23.0
