### ISSUE TITLE
Adding accept-range support?

### ISSUE THREAD

**Issue by CliffHan** [lipanski/mockito#91]
I could add a file by "with_body_from_file()" method, but I couldn't find a way simply adding the "range" support with mockito.

Could it be handled within?

**Comment by lipanski** [comment]
@CliffHan what do you mean by the "range" support? can you provide an example or your use case?

**Comment by CliffHan** [comment]
I'd like to test a client which send a http request with "range" in request header.
For example, a request has the "range=0-1023" in the header, means it expects the first 1024 bytes of the file.
With current mockito, it seems that I had to make lots of mocks with different matchers of different ranges, and set the body with different part of the response file.

**Comment by lipanski** [comment]
You can probably solve this with `Mock::with_body_from_request` and `Mock::with_header_from_request` these days.
