### ISSUE TITLE
Add support for multiple endpoints

### ISSUE THREAD

**Issue by zacps** [lipanski/mockito#94]
I'm testing an application which has support for falling back to other endpoints. Because the server is known the API url never changes and isn't configurable.

I want to test that parts of the application will correctly fall back to other endpoints if they're configured. To do that I would need the ability to start additional mock servers with their own mocks.

**Comment by lipanski** [comment]
@zacps would the solution proposed in https://github.com/lipanski/mockito/issues/92 work for you? if so, we could look into implementing that.

**Comment by johannescpk** [comment]
Personally I'd say the solution proposed in #92 would fit nicely here. I'm also having that use case where I have multiple endpoints that are exclusively used in tests, such as mocking away an external service

**Comment by lipanski** [comment]
Fixed in https://github.com/lipanski/mockito/releases/tag/0.32.0
