### ISSUE TITLE
Lifetime documentation seems incorrect

### ISSUE THREAD

**Issue by ggriffiniii** [lipanski/mockito#96]
I think the lifetime documentation is a little incorrect and misleading. I've pasted the section of the documentation below for reference. In the example it's noted that _m1 and _m2 require different names, but I don't believe that's true. It would have the same behavior even if they were both called _m. Adding a new let binding will not change the lifetime of a previous let binding of the same name, it just makes it no longer accessible in subsequent code. Note that this is true even without the enclosing scope surrounding _m2.

# Lifetime

Just like any Rust object, a mock is available only through its lifetime. You'll want to assign
the mocks to variables in order to extend and control their lifetime.

Avoid using the underscore matcher when creating your mocks, as in `let _ = mock("GET", "/")`.
This will end your mock's lifetime immediately. You can still use the underscore to prefix your variable
names in an assignment, but don't limit it to just this one character.

## Example

```
use mockito::mock;

let _m1 = mock("GET", "/long").with_body("hello").create();

{
    let _m2 = mock("GET", "/short").with_body("hi").create();

    // Requests to GET /short will be mocked til here
}

// Requests to GET /long will be mocked til here
```

Note how I **didn't use the same variable name** for both mocks (e.g. `let _m`), as it would have ended the
lifetime of the first mock with the second assignment.

**Comment by lipanski** [comment]
yup, seems like it. don't remember exactly the context back when I wrote that, could be that this was covered in a later Rust version or my test was faulty.

fixed by https://github.com/lipanski/mockito/commit/b65d5b70e349ef52a1d1e7a4c0ea3d3a5ff47b99
