### ISSUE TITLE
Different responses for the same endpoint

### ISSUE THREAD

**Issue by xneomac** [lipanski/mockito#97]
I would like to write theses mocks and I would like the first response to be a 200 and the next 4 to be 404.

```
let mock_ok = mock("GET", "/next")
    .with_status(200)
    .create();

let mock_bad = mock("GET", "/next")
    .with_status(404)
    .expect(4)
    .create();

mock_ok.assert();
mock_bad.assert();
```
Is it already possible? Can it be an interesting feature?

**Comment by lipanski** [comment]
Released in [0.25.0](https://github.com/lipanski/mockito/releases/tag/0.25.0).
